---
- hosts: all
  roles:
    - { role: dotstrap.xcode, xcode_colorthemes: {} }
    - {
      role: geerlingguy.homebrew,
      homebrew_installed_packages: [
        { name: node },
        { name: wget },
        { name: nmap },
        { name: ansible },
        { name: cmake },
        { name: doxygen },
        { name: graphviz }
      ],
      homebrew_taps: [
        kabel/php-ext,
        homebrew/cask
      ],
      homebrew_cask_apps: [
        docker,
        virtualbox,
        virtualbox-extension-pack,
        phantomjs
      ]
    }
    - zsh
    - {
      role: vim,
      packages: [
        { name: vim-monokai, vendor: sickill },
        { name: vim-multiple-cursors, vendor: terryma },
        { name: YouCompleteMe, vendor: Valloric },
        { name: vim-ags, vendor: gabesoft }
      ]
    }
    - {
      role: webserver-php
    }
    - {
      role: web-tools,
      brew_packages: [],
      npm_packages: [
        { name: grunt },
        { name: grunt-cli },
        { name: gulp },
        { name: gulp-cli }
      ],
      gem_packages: [
        { name: bundler },
        { name: sass }
      ],
      composer_packages: {
        name: hirak/prestissimo
      },
      pip_packages: {}
    }
    - {
      role: sublime
    }