---
# tasks file for web-tools
- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: install npm
  homebrew:
    name: npm
    state: latest

- name: install wget
  homebrew:
    name: wget
    state: latest

- name: install nmap
  homebrew:
    name: nmap
    state: latest

- name: install ansible
  homebrew:
    name: ansible
    state: latest

- name: install zsh
  homebrew:
    name: zsh
    state: latest

- name: install zsh-completions
  homebrew:
    name: zsh-completions
    state: latest

- name: install vim
  homebrew:
    name: vim
    state: latest

- name: install bundler
  #  become: yes
  gem:
    name: bundler

- name: install sass
  #  become: yes
  gem:
    name: sass

- include_role:
    name: macos-ohmyzsh

- include_role:
    name: ctorgalson.janus

- git:
    repo: 'https://github.com/sickill/vim-monokai.git'
    dest: '{{ ansible_env.HOME }}/.janus/vim-monokai'
