---
# tasks file for zsh
- name: ensure homebrew is updated
  homebrew:
    state: latest
    update_homebrew: yes

- name: install zsh
  homebrew:
    name: zsh
    state: latest

- name: copy dotfile
  copy:
    src: .zshrc
    dest: "{{ ansible_env.HOME }}/."
    force: no

- name: install zsh-completions
  homebrew:
    name: zsh-completions
    state: latest

- include_role:
    name: macos-ohmyzsh
