---
# defaults file for webserver-php
# waiting for https://github.com/Homebrew/homebrew-core/pull/26137
homebrew_installed_packages: [
  { name: dnsmasq },
  { name: mongodb },
  { name: mariadb },
  { name: httpd },
  { name: autoconf },
  { name: pkg-config },
  { name: gnu-sed }
]

php_valid_options: [
  {
    name: 'php@5.6',
    shortname: '56',
    version: '5.6',
    extensions: [
      { name: pecl_http-2.6.0 },
      { name: APCu-4.0.11 },
      { name: uploadprogress },
      { name: xdebug-2.5.5 },
      { name: yaml-1.3.1 }
    ]
  },
  {
    name: 'php@7.0',
    shortname: '70',
    version: '7.0',
    extensions: [
      { name: pecl_http },
      { name: uploadprogress },
      { name: xdebug },
      { name: yaml }
    ]
  },
  {
    name: 'php@7.1',
    shortname: '71',
    version: '7.1',
    extensions: [
      { name: pecl_http },
      { name: uploadprogress },
      { name: xdebug },
      { name: yaml }
    ]
  },
  {
    name: 'php@7.2',
    shortname: '72',
    version: '7.2',
    extensions: [
      { name: pecl_http },
      { name: uploadprogress },
      { name: xdebug },
      { name: yaml }
    ]
  }
]