---
# tasks file for sublime
# install sublime text
- name: Check brew list
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: "app_list"
  command: "ls /Applications"

- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: [
    caskroom/fonts
  ]

- name: install sublime text 3
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: [
    sublime-text,
    font-sourcecodepro-nerd-font
  ]
  when: "'sublime' not in app_list.stdout"

# ensure folder
- name: create settings dir
  file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages/User"
    state: directory

# copy prefs
- name: copy prefs
  copy:
    src: Preferences.sublime-settings
    dest: ~/Library/Application Support/Sublime Text 3/Packages/User/.
    force: no

# ensure subl
- name: ensure sublime symlink
  file:
    src: "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
    dest: "/usr/local/bin/subl"
    state: link

# - name: Download packagemanager
#   get_url:
#     url: https://packagecontrol.io/Package%20Control.sublime-package
#     dest: ~/Library/Application Support/Sublime Text 3/Installed Packages/.

- name: install packages
  git:
    repo: https://github.com/{{ item.repo }}
    version: master
    dest: "~/Library/Application Support/Sublime Text 3/Packages/User/{{ item.name }}"
  with_items: [
    {
      repo: jonschlinkert/sublime-monokai-extended.git,
      name: SublimeLinter/Monokai-Extended
    },
    {
      repo: jamiewilson/predawn.git,
      name: predawn
    },
    {
      repo: asbjornenge/Docker.tmbundle.git,
      name: Docker.tmbundle
    },
    {
      repo: robballou/drupal-sublimetext.git,
      name: Drupal
    },
    {
      repo: SublimeText/GenerateUUID.git,
      name: GenerateUUID
    },
    {
      repo: BrianGilbert/Sublime-Text-2-Goto-Drupal-API.git,
      name: GotoDocumentation
    },
    {
      repo: purplefish32/sublime-text-2-wordpress.git,
      name: Wordpress
    },
    {
      repo: brandonwamboldt/sublime-nginx.git,
      name: nginx
    },
    {
      repo: Anomareh/PHP-Twig.tmbundle.git,
      name: PHP-Twig.tmbundle
    },
    {
      repo: P233/Syntax-highlighting-for-Sass.git,
      name: Sass
    },
    {
      repo: SublimeLinter/SublimeLinter.git,
      name: SublimeLinter
    },
    {
      repo: SublimeLinter/SublimeLinter-jshint.git,
      name: SublimeLinter-jshint
    },
    {
      repo: SublimeLinter/SublimeLinter-php.git,
      name: SublimeLinter-php
    },
    {
      repo: SublimeLinter/SublimeLinter-ruby.git,
      name: SublimeLinter-ruby
    },
    {
      repo: SublimeLinter/SublimeLinter-pylint.git,
      name: SublimeLinter-pylint
    },
    {
      repo: SublimeLinter/SublimeLinter-csslint.git,
      name: SublimeLinter-csslint
    },
    {
      repo: SublimeLinter/SublimeLinter-eslint.git,
      name: SublimeLinter-eslint
    },
    {
      repo: SublimeLinter/SublimeLinter-json.git,
      name: SublimeLinter-json
    },
    {
      repo: clifford-github/sublime-ansible.git,
      name: ansible
    },
    {
      repo: buymeasoda/soda-theme.git,
      name: "Theme - Soda"

    }

  ]


# install packages
- name: install packages
  include_role:
    name: igor_mukhin.sublimetext3_packagecontrol
  vars:
    packagecontrol_dir_bin: "~/Library/Application Support/Sublime Text 3/Installed Packages"
    packagecontrol_dir_cfg: "~/Library/Application Support/Sublime Text 3/Packages/User"
    packagecontrol_owner: "{{ ansible_env.USER }}"
    packagecontrol_group: "staff"
    packagecontrol_packages: [
      "Predawn",
      "Dockerfile Syntax Highlighting",
      "Drupal",
      "GenerateUUID",
      "GotoDocumentation",
      "Wordpress",
      "nginx",
      "PHP-Twig",
      "Sass",
      "SublimeLinter",
      "SublimeLinter-jshint",
      "SublimeLinter-php",
      "SublimeLinter-ruby",
      "SublimeLinter-pylint",
      "SublimeLinter-csslint",
      "SublimeLinter-eslint",
      "SublimeLinter-json",
      "Ansible",
      "Package Control",
      "Theme - Soda",
      "Theme - Soda SolarizedDark"
    ]

