---
# tasks file for sublime
# install sublime text
- name: Check brew list
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: "app_list"
  command: "ls /Applications"

- name: Ensure configured taps are tapped.
  homebrew_tap: "tap={{ item }} state=present"
  with_items: [
    homebrew/cask-fonts
  ]

- name: install sublime text 3
  homebrew_cask:
    name: "{{ item }}"
    state: present
  with_items: [
    sublime-text,
    font-sourcecodepro-nerd-font
  ]
  when: "'sublime' not in app_list.stdout"

# ensure folder
- name: create settings dir
  file:
    path: "{{ ansible_env.HOME }}/Library/Application Support/Sublime Text 3/Packages/User"
    state: directory

# copy prefs
- name: copy prefs
  copy:
    src: Preferences.sublime-settings
    dest: ~/Library/Application Support/Sublime Text 3/Packages/User/.
    force: yes

# ensure subl
- name: ensure sublime symlink
  file:
    src: "/Applications/Sublime Text.app/Contents/SharedSupport/bin/subl"
    dest: "/usr/local/bin/subl"
    state: link

# install packages
- name: install packages
  include_role:
    name: igor_mukhin.sublimetext3_packagecontrol
  vars:
    packagecontrol_dir_bin: "~/Library/Application Support/Sublime Text 3/Installed Packages"
    packagecontrol_dir_cfg: "~/Library/Application Support/Sublime Text 3/Packages/User"
    packagecontrol_owner: "{{ ansible_env.USER }}"
    packagecontrol_group: "staff"
    packagecontrol_packages: [
      "Predawn",
      "Dockerfile Syntax Highlighting",
      "Drupal",
      "GenerateUUID",
      "Goto Drupal API",
      "GotoDocumentation",
      "Wordpress",
      "nginx",
      "PHP-Twig",
      "Sass",
      "SublimeLinter",
      "SublimeLinter-jshint",
      "SublimeLinter-php",
      "SublimeLinter-ruby",
      "SublimeLinter-pylint",
      "SublimeLinter-csslint",
      "SublimeLinter-eslint",
      "SublimeLinter-json",
      "Ansible",
      "Package Control",
      "Theme - Soda",
      "Theme - Soda SolarizedDark",
      "Monokai Extended",
      "Monokai Neue"
    ]

