---
- name: Check if drush launcher is installed.
  stat:
    path: /usr/local/bin/drush
  register: drush_bin

- name: Download drush launcher.
  get_url:
    url: https://github.com/drush-ops/drush-launcher/releases/download/0.6.0/drush.phar
    dest: /usr/local/bin/drush
    mode: 0755
  when: not drush_bin.stat.exists


