---
# tasks file for webserver-php
# install packages
- name: Install brew webserver elements
  homebrew:
    name: "{{ item.name | default(item) }}"
  with_items: "{{ homebrew_installed_packages }}"

- name: Install brew php versions
  homebrew:
    name: "{{ item.name | default(item) }}"
  with_items: "{{ php_valid_options }}"

- name: Check brew list
  environment:
    PATH: "/usr/local/bin:{{ ansible_env.PATH }}"
  register: "brew_list"
  command: "ls /usr/local/opt"

- name: create php7.2 symlink for more consistency
  file:
    src: "/usr/local/opt/php"
    dest: "/usr/local/opt/php@7.2"
    state: link
  when: "'php@7.2' in brew_list.stdout"

# copy shell script for compiling mongo ext
- name: copy compiling mongo ext script
  copy:
    src: buildmongoext.sh
    dest: "/tmp/."

# install php packages
- name: install php extensions
  include_tasks: php.yml
  vars:
    phpversion: "{{ item }}"
  when: item.name in brew_list.stdout
  with_items: "{{ php_valid_options }}"

# cleanup
- name: delete compiling mongo ext script
  file:
    state: absent
    path: "/tmp/buildmongoext.sh"

# create fcgi

# add resolver
# add dnsmasq config
# add apache config
# generate ssl
# add ca to keychain

# add documents folder
# add adminer
# add testfolder